module Library

let libraryFiles = [
    "foreign.scm"
    "numbers.scm"
    "symbols.scm"
    "random.scm"
    "vector.scm"
    "strings.scm"
    "lists.scm"
    "output-port.scm"
    "input-port.scm"
    "output.scm"
    "input.scm"
]

let libraryFunctions = [
    "error"
    "abs"
    "string->symbol"
    "list"
    "empty?"
    "memq"
    "list?"
    "length"
    "string=?"
    "vector"
    "vector-swap!"
    "vector-shuffle!"
    "output-port?"
    "open-output-file"
    "close-output-port"
    "flush-output-port"
    "current-output-port"
    "input-port?"
    "open-input-file"
    "close-input-port"
    "current-input-port"
    "write-char"
    "read-char"
    "read-char*"
    "newline"
    "exit-scheme"
    "read-int"
    "write-string"
    "write-int"
    "append"
    "filter"
    "for-each"
    "reverse"
    "rand-next"
]