module Primitive

type Prim =
    | Add
    | Sub
    | Mul
    | Sar
    | Quotient
    | Remainder
    | Eq
    | Lt
    | Le
    | Gt
    | Ge
    | Not
    | IsFixnum
    | IsBoolean
    | Cons
    | IsPair
    | IsNull
    | Car
    | Cdr
    | SetCar
    | SetCdr
    | MakeVector
    | IsVector
    | VectorLength
    | VectorRef
    | VectorSet
    | MakeString
    | IsString
    | StringLength
    | StringRef
    | StringSet
    | StringInit
    | MakeClosure
    | ClosureRef
    | IsProcedure
    | GlobalRef
    | GlobalRefUncheck // Do not check before read.
    | GlobalSet
    | IsZero
    | NumberToChar
    | CharToNumber
    | IsChar
    | Apply
    | MakeSymbol
    | SymbolString
    | IsSymbol
    | EofObject
    | IsEofObject
    | Collect
    | CheckFreePointer

let stringPrimop = [
    "+", Add
    "-", Sub
    "fx+", Add
    "fx-", Sub
    "*", Mul
    "fx*", Mul
    "quotient", Quotient
    "remainder", Remainder
    "eq?", Eq
    "=", Eq
    "<", Lt
    "<=", Le
    ">", Gt
    ">=", Ge
    "not", Not
    "fixnum?", IsFixnum
    "number?", IsFixnum
    "boolean?", IsBoolean
    "cons", Cons
    "pair?", IsPair
    "null?", IsNull
    "car", Car
    "cdr", Cdr
    "set-car!", SetCar
    "set-cdr!", SetCdr
    "make-vector", MakeVector
    "vector?", IsVector
    "vector-length", VectorLength
    "vector-ref", VectorRef
    "vector-set!", VectorSet
    "make-string", MakeString
    "string?", IsString
    "string-length", StringLength
    "string-ref", StringRef
    "string-set!", StringSet
    "procedure?", IsProcedure
    "zero?", IsZero
    "fxzero?", IsZero
    "number->char", NumberToChar
    "char->number", CharToNumber
    "fixnum->char", NumberToChar
    "char->fixnum", CharToNumber
    "char?", IsChar
    "apply", Apply
    "make-symbol", MakeSymbol
    "symbol-string", SymbolString
    "symbol?", IsSymbol
    // "error", Error
    "eof-object", EofObject
    "eof-object?", IsEofObject
]
