(foreign-call "printPtr" (read-char (current-input-port)))
(foreign-call "printPtr" (read-char (current-input-port)))
(foreign-call "printPtr" (read-char (current-input-port)))
(foreign-call "printPtr" (read-char (current-input-port)))
(foreign-call "printPtr" (read-char (current-input-port)))
(foreign-call "printPtr" (read-char (current-input-port)))
