(let ([ip (open-input-file "misc/scratch.txt")])
    (foreign-call "printPtr" (read-char ip))
    (foreign-call "printPtr" (read-char ip))
    (foreign-call "printPtr" (read-char ip))
    (foreign-call "printPtr" (read-char ip))
    (foreign-call "printPtr" (read-char ip))
    (foreign-call "printPtr" (read-char ip)))
(exit-scheme)